### ISSUE TITLE
Add ability to specify a default subcommand

### ISSUE THREAD

**Issue by ntwcklng** [leo/args#84]
Just like `now` running `now deploy` by default, we could add the ability to specify a default subcommand.
Maybe like this:
`.defaultCommand('deploy', 'Deploy')` or
`.command('deploy', 'Deploy', { defaultCommand: true }`
or via the `options` in `.parse(process.argv, { defaultCommand: 'deploy' }`

**Comment by leo** [comment]
@jcurtis You should try [this](https://github.com/leo/args#showhelp)... 😊

**Comment by jcurtis** [comment]
@leo Yep using `.showHelp()`. The problem is that the execution doesn't stop after a command has been run and there's no readily apparent way to know if a command was successfully found without having to check the `process.argv` input manually. 

I was thinking since we're already holding the list of valid commands within the `args` instance maybe it would make sense to check for a valid command there. 

Maybe a better approach would be to expose something like `args.validSubCommand()` so users can more easily check it themselves? 

[`.isDefined`](https://github.com/leo/args/blob/master/index.js#L486) is kinda relevant but you'd still need internals to call it. 

Here's a third idea: instead of only returning `flags` on `args.parse(process.argv)` we could return an object with a bit more information in it. This would obviously be a breaking changes though. 

```
const {command, flags} = args.parse(process.argv);
```

**Comment by ntwcklng** [comment]
@jcurtis `args.sub` returns an array of all subcommands from `process.argv`. e.g.
```js
const args = require('args');

args.command('import', 'Import Command')

console.log(args.sub)

args.parse(process.argv)

if (!args.sub[0]) args.showHelp() // calling the script without a subcommand will show help
```
```sh
$ node script.js
[]
$ node script.js import
['import']
```

**Comment by jcurtis** [comment]
It does for showing the help screen. Thanks 👍 

What about the default command scenario? Same logic except you'd want to call `import` for example?

**Comment by leo** [comment]
After `.parse()`, the execution WILL stop. So if you're defining the sub commands on top of your main binary (that's where they should be defined), args will run the command if found and if it doesn't find one with the name entered, it will go on with running the main binary. In turn, you only need to call `.showHelp` there after you've defined the commands and the help will show up if the user tried to run a sub command that doesn't exist.

**Comment by leo** [comment]
The default command should be the code contained within the main binary. If you need an alias for that, simply define a new command and make it load the main binary.

You can define it in the `init` function [here](https://github.com/leo/args/blob/master/readme.md#commandname-description-init-aliases).
